services:
  - type: web
    name: criticsapp-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_ORIGIN
        sync: false
