const mongoose = require('mongoose');
require('dotenv').config();
const Content = require('./models/Content');

const seedData = [
  // --- SCI-FI & ACTION ---
  {
    title: 'Inception',
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    year: 2010,
    poster_url: 'https://image.tmdb.org/t/p/original/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/8ZTVqvKdQ8emSGUOM96WAelqi86.jpg',
    imdb_rating: 8.8,
    meta_score: 74,
    certificate: 'PG-13',
    no_of_votes: 2400000,
    gross: '$292M',
    genre: 'Action, Sci-Fi, Thriller',
    duration: '148 min',
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
    quote: 'Smart, innovative, and thrilling, Inception is that rare summer blockbuster that succeeds viscerally as well as intellectually.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 91,
    critics_score: 87,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: '8hP9D6kZseM',
    youtube_url: 'https://www.youtube.com/watch?v=8hP9D6kZseM',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'Interstellar',
    synopsis: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    year: 2014,
    poster_url: 'https://image.tmdb.org/t/p/original/gEU2QniE6E77NI6lCU6MvrId35O.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/pbrkL804c8yAv3zBZR4QPEafpAR.jpg',
    imdb_rating: 8.6,
    meta_score: 74,
    certificate: 'PG-13',
    no_of_votes: 1900000,
    gross: '$188M',
    genre: 'Adventure, Drama, Sci-Fi',
    duration: '169 min',
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Mackenzie Foy'],
    quote: 'Interstellar represents more of the thrilling, thought-provoking, and visually resplendent filmmaking moviegoers have come to expect from writer-director Christopher Nolan.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 86,
    critics_score: 73,
    trending: true,
    critics_picks: false,
    content_type: 'Movie',
    trailer_youtube_id: 'zSWdZVtXT7E',
    youtube_url: 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'The Dark Knight',
    synopsis: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    year: 2008,
    poster_url: 'https://image.tmdb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
    imdb_rating: 9.0,
    meta_score: 84,
    certificate: 'PG-13',
    no_of_votes: 2700000,
    gross: '$534M',
    genre: 'Action, Crime, Drama',
    duration: '152 min',
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
    quote: 'Dark, complex and unforgettable, The Dark Knight succeeds not just as an entertaining comic book film, but as a richly thrilling crime saga.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 94,
    critics_score: 94,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'EXeTwQWrcwY',
    youtube_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'Dune',
    synopsis: 'Feature adaptation of Frank Herbert\'s science fiction novel, about the son of a noble family entrusted with the protection of the most valuable asset and most vital element in the galaxy.',
    year: 2021,
    poster_url: 'https://image.tmdb.org/t/p/original/d5NXSklXo0qyIYkgV94XAgMIckC.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/lzWHmYdfeFiMIY4JaMmtR7GEli3.jpg',
    imdb_rating: 8.0,
    meta_score: 74,
    certificate: 'PG-13',
    no_of_votes: 800000,
    gross: '$108M',
    genre: 'Action, Adventure, Drama, Sci-Fi',
    duration: '155 min',
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Zendaya', 'Oscar Isaac'],
    quote: 'Dune occasionally struggles with its unwieldy source material, but those issues are largely overshadowed by the scope and ambition of this visually thrilling adaptation.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 90,
    critics_score: 83,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'n9xhKvEQQbI',
    youtube_url: 'https://www.youtube.com/watch?v=n9xhKvEQQbI',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'The Matrix',
    synopsis: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    year: 1999,
    poster_url: 'https://image.tmdb.org/t/p/original/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/ncEsesgOJDNrTUED89hYbA117wo.jpg',
    imdb_rating: 8.7,
    meta_score: 73,
    certificate: 'R',
    no_of_votes: 1900000,
    gross: '$171M',
    genre: 'Action, Sci-Fi',
    duration: '136 min',
    director: 'Lana Wachowski, Lilly Wachowski',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    quote: 'Thanks to the Wachowskis\' imaginative vision, The Matrix is a smartly crafted combination of spectacular action and groundbreaking special effects.',
    resolution: '4K Ultra HD',
    audio: '5.1 Surround',
    user_score: 85,
    critics_score: 88,
    trending: false,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'vKQi3bNUM1Y',
    youtube_url: 'https://www.youtube.com/watch?v=vKQi3bNUM1Y',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },

  // --- DRAMA & THRILLER ---
  {
    title: 'The Shawshank Redemption',
    synopsis: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    year: 1994,
    poster_url: 'https://image.tmdb.org/t/p/original/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    imdb_rating: 9.3,
    meta_score: 80,
    certificate: 'R',
    no_of_votes: 2700000,
    gross: '$28M',
    genre: 'Drama',
    duration: '142 min',
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler'],
    quote: 'The Shawshank Redemption is an uplifting, deeply satisfying prison drama with sensitive, outstanding direction and performances.',
    resolution: '4K Ultra HD',
    audio: '5.1 Surround',
    user_score: 98,
    critics_score: 91,
    trending: false,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: '6hB3S9bIaco',
    youtube_url: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'The Godfather',
    synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    year: 1972,
    poster_url: 'https://image.tmdb.org/t/p/original/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
    imdb_rating: 9.2,
    meta_score: 100,
    certificate: 'R',
    no_of_votes: 1900000,
    gross: '$134M',
    genre: 'Crime, Drama',
    duration: '175 min',
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Diane Keaton'],
    quote: 'One of Hollywood\'s greatest critical and commercial successes, The Godfather gets everything right.',
    resolution: '4K Ultra HD',
    audio: '5.1 Surround',
    user_score: 98,
    critics_score: 97,
    trending: false,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'UaVTIH8mujA',
    youtube_url: 'https://www.youtube.com/watch?v=UaVTIH8mujA',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'Parasite',
    synopsis: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    year: 2019,
    poster_url: 'https://image.tmdb.org/t/p/original/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
    imdb_rating: 8.5,
    meta_score: 96,
    certificate: 'R',
    no_of_votes: 850000,
    gross: '$53M',
    genre: 'Comedy, Drama, Thriller',
    duration: '132 min',
    director: 'Bong Joon Ho',
    cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'],
    quote: 'An urgent, brilliantly layered look at timely social themes, Parasite finds writer-director Bong Joon Ho in near-total command of his craft.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 90,
    critics_score: 99,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: '5xH0HfJHsaY',
    youtube_url: 'https://www.youtube.com/watch?v=5xH0HfJHsaY',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'Joker',
    synopsis: 'A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.',
    year: 2019,
    poster_url: 'https://image.tmdb.org/t/p/original/udDclJoHjfpt8MvSMzT87522XnE.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmIyHQdXOUX9mXh.jpg',
    imdb_rating: 8.4,
    meta_score: 59,
    certificate: 'R',
    no_of_votes: 1300000,
    gross: '$335M',
    genre: 'Crime, Drama, Thriller',
    duration: '122 min',
    director: 'Todd Phillips',
    cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz', 'Frances Conroy'],
    quote: 'Joker gives its infamous central character a chillingly plausible origin story that serves as a brilliant showcase for its star.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 88,
    critics_score: 68,
    trending: true,
    critics_picks: false,
    content_type: 'Movie',
    trailer_youtube_id: 'zAGVQLHvwOY',
    youtube_url: 'https://www.youtube.com/watch?v=zAGVQLHvwOY',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },

  // --- ANIMATION & FAMILY ---
  {
    title: 'Spider-Man: Into the Spider-Verse',
    synopsis: 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.',
    year: 2018,
    poster_url: 'https://image.tmdb.org/t/p/original/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg',
    imdb_rating: 8.4,
    meta_score: 87,
    certificate: 'PG',
    no_of_votes: 590000,
    gross: '$190M',
    genre: 'Animation, Action, Adventure',
    duration: '117 min',
    director: 'Bob Persichetti, Peter Ramsey, Rodney Rothman',
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld', 'Mahershala Ali'],
    quote: 'Spider-Man: Into the Spider-Verse matches bold storytelling with striking animation for a purely enjoyable adventure.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 93,
    critics_score: 97,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'g4Hbz2jLxvQ',
    youtube_url: 'https://www.youtube.com/watch?v=g4Hbz2jLxvQ',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'Spirited Away',
    synopsis: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    year: 2001,
    poster_url: 'https://image.tmdb.org/t/p/original/39wmItIWsg5sZMyRUHLkBg8lWNO.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/bSXfU4dwZyBA1vMmXvejdRXBCTF.jpg',
    imdb_rating: 8.6,
    meta_score: 96,
    certificate: 'PG',
    no_of_votes: 790000,
    gross: '$15M',
    genre: 'Animation, Adventure, Family',
    duration: '125 min',
    director: 'Hayao Miyazaki',
    cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki', 'Takashi Naitô'],
    quote: 'Spirited Away is a dazzling, enchanting, and gorgeously drawn fairy tale that will leave viewers a little more curious and fascinated by our world.',
    resolution: '1080p HD',
    audio: '5.1 Surround',
    user_score: 96,
    critics_score: 97,
    trending: false,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'ByXuk9QqQkk',
    youtube_url: 'https://www.youtube.com/watch?v=ByXuk9QqQkk',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'WALL·E',
    synopsis: 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
    year: 2008,
    poster_url: 'https://image.tmdb.org/t/p/original/hbhFnRzzg6ZDmm8YAmxBlCsy432.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/fK5ssgvtI43z19FoKsNCyloKICN.jpg',
    imdb_rating: 8.4,
    meta_score: 95,
    certificate: 'G',
    no_of_votes: 1100000,
    gross: '$223M',
    genre: 'Animation, Adventure, Family',
    duration: '98 min',
    director: 'Andrew Stanton',
    cast: ['Ben Burtt', 'Elissa Knight', 'Jeff Garlin', 'Fred Willard'],
    quote: 'WALL-E\'s stellar visuals testify once again to Pixar\'s ingenuity, while its charming star will captivate viewers of all ages.',
    resolution: '4K Ultra HD',
    audio: '5.1 Surround',
    user_score: 90,
    critics_score: 95,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'CZ1CATNcXmM',
    youtube_url: 'https://www.youtube.com/watch?v=CZ1CATNcXmM',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },

  // --- BOLLYWOOD & INTERNATIONAL ---
  {
    title: '3 Idiots',
    synopsis: 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.',
    year: 2009,
    poster_url: 'https://image.tmdb.org/t/p/original/66A9MqXOyVFCssoloscw79zH021.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/uJqa1R3wPzRuzJ2Eha08DvtLOfZ.jpg',
    imdb_rating: 8.4,
    meta_score: 67,
    certificate: 'UA',
    no_of_votes: 410000,
    gross: '$6M',
    genre: 'Comedy, Drama',
    duration: '170 min',
    director: 'Rajkumar Hirani',
    cast: ['Aamir Khan', 'Madhavan', 'Mona Singh', 'Sharman Joshi'],
    quote: '3 Idiots is a hilarious, uplifting, and incredibly heartwarming film that challenges the traditional education system.',
    resolution: '1080p HD',
    audio: '5.1 Surround',
    user_score: 93,
    critics_score: 100,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'K0eDlFX9GMc',
    youtube_url: 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'Dangal',
    synopsis: 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.',
    year: 2016,
    poster_url: 'https://image.tmdb.org/t/p/original/1sApsgQ2nEusvENYn8LgS33s7O9.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/4u1xqaEbx2EaL10eFjPymqQZJ9g.jpg',
    imdb_rating: 8.3,
    meta_score: null,
    certificate: 'U',
    no_of_votes: 197000,
    gross: '$12M',
    genre: 'Action, Biography, Drama',
    duration: '161 min',
    director: 'Nitesh Tiwari',
    cast: ['Aamir Khan', 'Sakshi Tanwar', 'Fatima Sana Shaikh', 'Sanya Malhotra'],
    quote: 'Dangal is a crowd-pleasing, thoroughly entertaining sports drama that packs a powerful emotional punch.',
    resolution: '1080p HD',
    audio: '5.1 Surround',
    user_score: 88,
    critics_score: 88,
    trending: false,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'x_7YlGv9u1g',
    youtube_url: 'https://www.youtube.com/watch?v=x_7YlGv9u1g',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },

  // --- RECENT BLOCKBUSTERS ---
  {
    title: 'Oppenheimer',
    synopsis: 'The story of American scientist, J. Robert Oppenheimer, and his role in the development of the atomic bomb.',
    year: 2023,
    poster_url: 'https://image.tmdb.org/t/p/original/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    imdb_rating: 8.6,
    meta_score: 88,
    certificate: 'R',
    no_of_votes: 500000,
    gross: '$326M',
    genre: 'Biography, Drama, History',
    duration: '180 min',
    director: 'Christopher Nolan',
    cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.'],
    quote: 'Oppenheimer marks another engrossing achievement from Christopher Nolan that benefits from Murphy\'s tour-de-force performance.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 91,
    critics_score: 93,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'uYPbbksJxIg',
    youtube_url: 'https://www.youtube.com/watch?v=uYPbbksJxIg',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'Top Gun: Maverick',
    synopsis: 'After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN\'s elite graduates on a mission.',
    year: 2022,
    poster_url: 'https://image.tmdb.org/t/p/original/62HCnUTziyWcpZBpCEzH2Z9H9rE.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/AaV1YIdWKnjAIAOe8OUIiM7Sqfl.jpg',
    imdb_rating: 8.3,
    meta_score: 78,
    certificate: 'PG-13',
    no_of_votes: 600000,
    gross: '$718M',
    genre: 'Action, Drama',
    duration: '130 min',
    director: 'Joseph Kosinski',
    cast: ['Tom Cruise', 'Jennifer Connelly', 'Miles Teller', 'Val Kilmer'],
    quote: 'Top Gun: Maverick pulls off a feat even trickier than a 4G inverted dive, delivering a long-belated sequel that surpasses its predecessor.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 99,
    critics_score: 96,
    trending: true,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'giXco2jaZ_4',
    youtube_url: 'https://www.youtube.com/watch?v=giXco2jaZ_4',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  {
    title: 'Avatar: The Way of Water',
    synopsis: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns, Jake must work with Neytiri and the army of the Na\'vi race to protect their home.',
    year: 2022,
    poster_url: 'https://image.tmdb.org/t/p/original/t6HIqrHezINNdie08Tqc71M8M4K.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg',
    imdb_rating: 7.6,
    meta_score: 67,
    certificate: 'PG-13',
    no_of_votes: 450000,
    gross: '$684M',
    genre: 'Action, Adventure, Fantasy, Sci-Fi',
    duration: '192 min',
    director: 'James Cameron',
    cast: ['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang'],
    quote: 'Narratively, it might be fairly standard stuff — but visually speaking, Avatar: The Way of Water is a stunningly immersive experience.',
    resolution: '4K Ultra HD',
    audio: 'Dolby Atmos',
    user_score: 92,
    critics_score: 76,
    trending: true,
    critics_picks: false,
    content_type: 'Movie',
    trailer_youtube_id: 'd9MyW72ELq0',
    youtube_url: 'https://www.youtube.com/watch?v=d9MyW72ELq0',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  },
  
  // --- MASTERPIECES ---
  {
    title: '12 Angry Men',
    synopsis: 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
    year: 1957,
    poster_url: 'https://image.tmdb.org/t/p/original/ow3wq89wM8qd5X7hWKx63Yy5Aww.jpg',
    backdrop_url: 'https://image.tmdb.org/t/p/original/3WjbxaqYB4vAbdUfdr5wbglZZtL.jpg',
    imdb_rating: 9.0,
    meta_score: 96,
    certificate: 'U',
    no_of_votes: 800000,
    gross: '$4M',
    genre: 'Crime, Drama',
    duration: '96 min',
    director: 'Sidney Lumet',
    cast: ['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam', 'John Fiedler'],
    quote: 'Sidney Lumet\'s feature debut is a superbly written, strikingly effective courtroom thriller that rightly stands as a modern classic.',
    resolution: '1080p HD',
    audio: 'Mono',
    user_score: 97,
    critics_score: 100,
    trending: false,
    critics_picks: true,
    content_type: 'Movie',
    trailer_youtube_id: 'TEN-2uTi2c0',
    youtube_url: 'https://www.youtube.com/watch?v=TEN-2uTi2c0',
    hls_stream_url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8'
  }
];

const seedDB = async () => {
  try {
    console.log('✅ Connected to MongoDB Atlas');
    await mongoose.connect(process.env.MONGODB_URI);

    console.log('🗑️  Cleared existing content collection');
    await Content.deleteMany({});

    await Content.insertMany(seedData);
    console.log(`🌱 Seeded ${seedData.length} premium movies!`);
    seedData.forEach(movie => {
      console.log(`   • ${movie.title} — TMDB Poster & Trailer Integrated`);
    });

  } catch (err) {
    console.error('❌ Error seeding data:', err);
  } finally {
    mongoose.connection.close();
    console.log('🔌 Disconnected from MongoDB');
    process.exit(0);
  }
};

seedDB();
