/**
 * seed.js — Database seeder for CriticsApp
 *
 * Seeds MongoDB with real IMDB movie data.
 * Run with: node seed.js (or npm run seed)
 *
 * Uses public Apple/Mux HLS test streams for the hls_stream_url field.
 * Replace with your own CloudFront/CDN URLs in production.
 */

require('dotenv').config();
const mongoose = require('mongoose');
const Content = require('./models/Content');

// Public HLS test streams for development
const HLS_STREAMS = [
  'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
  'https://test-streams.mux.dev/pts_shift/master.m3u8',
];

const MONGODB_URI =
  process.env.MONGODB_URI || 'mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD@YOUR_CLUSTER.mongodb.net/criticsapp?retryWrites=true&w=majority';

/**
 * Seed data — mapped from the IMDB Top 250 dataset.
 * Each item is transformed to match the Mongoose Content schema.
 * Top-rated films (IMDB >= 8.8) are flagged as critics_picks.
 * Recent popular films are flagged as trending.
 */
const seedData = [
  {
    title: 'The Shawshank Redemption',
    synopsis: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    year: 1994,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 9.3,
    meta_score: 80,
    critics_score: 93,
    certificate: 'A',
    duration: '142 min',
    genre: 'Drama',
    director: 'Frank Darabont',
    cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler'],
    no_of_votes: 2343110,
    gross: '28,341,469',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'The Godfather',
    synopsis: "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
    year: 1972,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR1,0,67,98_AL_.jpg',
    imdb_rating: 9.2,
    meta_score: 100,
    critics_score: 92,
    certificate: 'A',
    duration: '175 min',
    genre: 'Crime, Drama',
    director: 'Francis Ford Coppola',
    cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Diane Keaton'],
    no_of_votes: 1620367,
    gross: '134,966,411',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: true,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'The Dark Knight',
    synopsis: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    year: 2008,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 9.0,
    meta_score: 84,
    critics_score: 90,
    certificate: 'UA',
    duration: '152 min',
    genre: 'Action, Crime, Drama',
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
    no_of_votes: 2303232,
    gross: '534,858,444',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'The Godfather: Part II',
    synopsis: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    year: 1974,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMWMwMGQzZTItY2JlNC00OWZiLWIyMDctNDk2ZDQ2YjRjMWQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR1,0,67,98_AL_.jpg',
    imdb_rating: 9.0,
    meta_score: 90,
    critics_score: 90,
    certificate: 'A',
    duration: '202 min',
    genre: 'Crime, Drama',
    director: 'Francis Ford Coppola',
    cast: ['Al Pacino', 'Robert De Niro', 'Robert Duvall', 'Diane Keaton'],
    no_of_votes: 1129952,
    gross: '57,300,000',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: true,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: '12 Angry Men',
    synopsis: 'A jury holdout attempts to prevent a miscarriage of justice by forcing his colleagues to reconsider the evidence.',
    year: 1957,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMWU4N2FjNzYtNTVkNC00NzQ0LTg0MjAtYTJlMjFhNGUxZDFmXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 9.0,
    meta_score: 96,
    critics_score: 90,
    certificate: 'U',
    duration: '96 min',
    genre: 'Crime, Drama',
    director: 'Sidney Lumet',
    cast: ['Henry Fonda', 'Lee J. Cobb', 'Martin Balsam', 'John Fiedler'],
    no_of_votes: 689845,
    gross: '4,360,000',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: false,
    content_type: 'Movie',
    technical_specs: 'HD, Stereo',
    resolution: 'HD',
    audio: 'Stereo',
  },
  {
    title: 'The Lord of the Rings: The Return of the King',
    synopsis: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    year: 2003,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.9,
    meta_score: 94,
    critics_score: 89,
    certificate: 'U',
    duration: '201 min',
    genre: 'Action, Adventure, Drama',
    director: 'Peter Jackson',
    cast: ['Elijah Wood', 'Viggo Mortensen', 'Ian McKellen', 'Orlando Bloom'],
    no_of_votes: 1642758,
    gross: '377,845,905',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Pulp Fiction',
    synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    year: 1994,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY98_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.9,
    meta_score: 94,
    critics_score: 89,
    certificate: 'A',
    duration: '154 min',
    genre: 'Crime, Drama',
    director: 'Quentin Tarantino',
    cast: ['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis'],
    no_of_votes: 1826188,
    gross: '107,928,762',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: "Schindler's List",
    synopsis: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.',
    year: 1993,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.9,
    meta_score: 94,
    critics_score: 89,
    certificate: 'A',
    duration: '195 min',
    genre: 'Biography, Drama, History',
    director: 'Steven Spielberg',
    cast: ['Liam Neeson', 'Ralph Fiennes', 'Ben Kingsley', 'Caroline Goodall'],
    no_of_votes: 1213505,
    gross: '96,898,818',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: true,
    trending: false,
    content_type: 'Movie',
    technical_specs: 'HD, Stereo',
    resolution: 'HD',
    audio: 'Stereo',
  },
  {
    title: 'Inception',
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    year: 2010,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.8,
    meta_score: 74,
    critics_score: 88,
    certificate: 'UA',
    duration: '148 min',
    genre: 'Action, Adventure, Sci-Fi',
    director: 'Christopher Nolan',
    cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Ken Watanabe'],
    no_of_votes: 2067042,
    gross: '292,576,195',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Fight Club',
    synopsis: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
    year: 1999,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMmEzNTkxYjQtZTc0MC00YTVjLTg5ZTEtZWMwOWVlYzY0NWIwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.8,
    meta_score: 66,
    critics_score: 88,
    certificate: 'A',
    duration: '139 min',
    genre: 'Drama',
    director: 'David Fincher',
    cast: ['Brad Pitt', 'Edward Norton', 'Meat Loaf', 'Zach Grenier'],
    no_of_votes: 1854740,
    gross: '37,030,102',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    synopsis: 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.',
    year: 2001,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.8,
    meta_score: 92,
    critics_score: 88,
    certificate: 'U',
    duration: '178 min',
    genre: 'Action, Adventure, Drama',
    director: 'Peter Jackson',
    cast: ['Elijah Wood', 'Ian McKellen', 'Orlando Bloom', 'Sean Bean'],
    no_of_votes: 1661481,
    gross: '315,544,750',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Forrest Gump',
    synopsis: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    year: 1994,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UY98_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.8,
    meta_score: 82,
    critics_score: 88,
    certificate: 'UA',
    duration: '142 min',
    genre: 'Drama, Romance',
    director: 'Robert Zemeckis',
    cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Sally Field'],
    no_of_votes: 1809221,
    gross: '330,252,182',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: true,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'The Matrix',
    synopsis: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    year: 1999,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.7,
    meta_score: 73,
    critics_score: 87,
    certificate: 'A',
    duration: '136 min',
    genre: 'Action, Sci-Fi',
    director: 'Lana Wachowski',
    cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving'],
    no_of_votes: 1676426,
    gross: '171,479,930',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Goodfellas',
    synopsis: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
    year: 1990,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.7,
    meta_score: 90,
    critics_score: 87,
    certificate: 'A',
    duration: '146 min',
    genre: 'Biography, Crime, Drama',
    director: 'Martin Scorsese',
    cast: ['Robert De Niro', 'Ray Liotta', 'Joe Pesci', 'Lorraine Bracco'],
    no_of_votes: 1020727,
    gross: '46,836,394',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'Interstellar',
    synopsis: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    year: 2014,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.6,
    meta_score: 74,
    critics_score: 86,
    certificate: 'UA',
    duration: '169 min',
    genre: 'Adventure, Drama, Sci-Fi',
    director: 'Christopher Nolan',
    cast: ['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Mackenzie Foy'],
    no_of_votes: 1512360,
    gross: '188,020,017',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Parasite',
    synopsis: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    year: 2019,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZDEyNDU4MmQyNzFkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.6,
    meta_score: 96,
    critics_score: 86,
    certificate: 'A',
    duration: '132 min',
    genre: 'Comedy, Drama, Thriller',
    director: 'Bong Joon Ho',
    cast: ['Kang-ho Song', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-sik'],
    no_of_votes: 552778,
    gross: '53,367,844',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K HDR10, Dolby Atmos',
    resolution: '4K HDR10',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Spirited Away',
    synopsis: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.',
    year: 2001,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.6,
    meta_score: 96,
    critics_score: 86,
    certificate: 'U',
    duration: '125 min',
    genre: 'Animation, Adventure, Family',
    director: 'Hayao Miyazaki',
    cast: ['Daveigh Chase', 'Suzanne Pleshette', 'Miyu Irino', 'Rumi Hiiragi'],
    no_of_votes: 651376,
    gross: '10,055,859',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'Saving Private Ryan',
    synopsis: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.',
    year: 1998,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZjhkMDM4MWItZTVjOC00ZDRhLThmYTAtM2I5NzBmNmNlMzI1XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.6,
    meta_score: 91,
    critics_score: 86,
    certificate: 'R',
    duration: '169 min',
    genre: 'Drama, War',
    director: 'Steven Spielberg',
    cast: ['Tom Hanks', 'Matt Damon', 'Tom Sizemore', 'Edward Burns'],
    no_of_votes: 1235804,
    gross: '216,540,909',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'The Green Mile',
    synopsis: 'The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.',
    year: 1999,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.6,
    meta_score: 61,
    critics_score: 86,
    certificate: 'A',
    duration: '189 min',
    genre: 'Crime, Drama, Fantasy',
    director: 'Frank Darabont',
    cast: ['Tom Hanks', 'Michael Clarke Duncan', 'David Morse', 'Bonnie Hunt'],
    no_of_votes: 1147794,
    gross: '136,801,374',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'Se7en',
    synopsis: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.',
    year: 1995,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.6,
    meta_score: 65,
    critics_score: 86,
    certificate: 'A',
    duration: '127 min',
    genre: 'Crime, Drama, Mystery',
    director: 'David Fincher',
    cast: ['Morgan Freeman', 'Brad Pitt', 'Kevin Spacey', 'Andrew Kevin Walker'],
    no_of_votes: 1445096,
    gross: '100,125,643',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, Dolby Atmos',
    resolution: '4K HDR10',
    audio: 'Dolby Atmos',
  },
  {
    title: 'The Silence of the Lambs',
    synopsis: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    year: 1991,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.6,
    meta_score: 85,
    critics_score: 86,
    certificate: 'A',
    duration: '118 min',
    genre: 'Crime, Drama, Thriller',
    director: 'Jonathan Demme',
    cast: ['Jodie Foster', 'Anthony Hopkins', 'Lawrence A. Bonney', 'Kasi Lemmons'],
    no_of_votes: 1270197,
    gross: '130,742,922',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'Joker',
    synopsis: "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime. This path brings him face-to-face with his alter-ego: the Joker.",
    year: 2019,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.5,
    meta_score: 59,
    critics_score: 85,
    certificate: 'A',
    duration: '122 min',
    genre: 'Crime, Drama, Thriller',
    director: 'Todd Phillips',
    cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz', 'Frances Conroy'],
    no_of_votes: 939252,
    gross: '335,451,311',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Whiplash',
    synopsis: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    year: 2014,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BOTA5NDZlZGUtMjAxOS00YTRkLTkwYmMtYWQ0NWEwZDZiNjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.5,
    meta_score: 88,
    critics_score: 85,
    certificate: 'A',
    duration: '106 min',
    genre: 'Drama, Music',
    director: 'Damien Chazelle',
    cast: ['Miles Teller', 'J.K. Simmons', 'Melissa Benoist', 'Paul Reiser'],
    no_of_votes: 717585,
    gross: '13,092,000',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'The Prestige',
    synopsis: 'After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.',
    year: 2006,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.5,
    meta_score: 66,
    critics_score: 85,
    certificate: 'U',
    duration: '130 min',
    genre: 'Drama, Mystery, Sci-Fi',
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Hugh Jackman', 'Scarlett Johansson', 'Michael Caine'],
    no_of_votes: 1190259,
    gross: '53,089,891',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'The Departed',
    synopsis: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    year: 2006,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.5,
    meta_score: 85,
    critics_score: 85,
    certificate: 'A',
    duration: '151 min',
    genre: 'Crime, Drama, Thriller',
    director: 'Martin Scorsese',
    cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson', 'Mark Wahlberg'],
    no_of_votes: 1189773,
    gross: '132,384,315',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Gladiator',
    synopsis: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    year: 2000,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.5,
    meta_score: 67,
    critics_score: 85,
    certificate: 'UA',
    duration: '155 min',
    genre: 'Action, Adventure, Drama',
    director: 'Ridley Scott',
    cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 'Oliver Reed'],
    no_of_votes: 1341460,
    gross: '187,705,427',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'The Lion King',
    synopsis: 'Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.',
    year: 1994,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMWNhYy00NjZiLWI0NjUtZmNhY2JhNDRmODU3XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.5,
    meta_score: 88,
    critics_score: 85,
    certificate: 'U',
    duration: '88 min',
    genre: 'Animation, Adventure, Drama',
    director: 'Roger Allers',
    cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones', 'Nathan Lane'],
    no_of_votes: 942045,
    gross: '422,783,777',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Back to the Future',
    synopsis: "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.",
    year: 1985,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.5,
    meta_score: 87,
    critics_score: 85,
    certificate: 'U',
    duration: '116 min',
    genre: 'Adventure, Comedy, Sci-Fi',
    director: 'Robert Zemeckis',
    cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson', 'Crispin Glover'],
    no_of_votes: 1058081,
    gross: '210,609,762',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'Django Unchained',
    synopsis: 'With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.',
    year: 2012,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.4,
    meta_score: 81,
    critics_score: 84,
    certificate: 'A',
    duration: '165 min',
    genre: 'Drama, Western',
    director: 'Quentin Tarantino',
    cast: ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio', 'Kerry Washington'],
    no_of_votes: 1357682,
    gross: '162,805,434',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Avengers: Endgame',
    synopsis: "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    year: 2019,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.4,
    meta_score: 78,
    critics_score: 84,
    certificate: 'UA',
    duration: '181 min',
    genre: 'Action, Adventure, Drama',
    director: 'Anthony Russo',
    cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Scarlett Johansson'],
    no_of_votes: 809955,
    gross: '858,373,000',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Spider-Man: Into the Spider-Verse',
    synopsis: 'Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.',
    year: 2018,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.4,
    meta_score: 87,
    critics_score: 84,
    certificate: 'U',
    duration: '117 min',
    genre: 'Animation, Action, Adventure',
    director: 'Bob Persichetti',
    cast: ['Shameik Moore', 'Jake Johnson', 'Hailee Steinfeld', 'Mahershala Ali'],
    no_of_votes: 375110,
    gross: '190,241,310',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: true,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'The Dark Knight Rises',
    synopsis: "Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.",
    year: 2012,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.4,
    meta_score: 78,
    critics_score: 84,
    certificate: 'UA',
    duration: '164 min',
    genre: 'Action, Adventure',
    director: 'Christopher Nolan',
    cast: ['Christian Bale', 'Tom Hardy', 'Anne Hathaway', 'Gary Oldman'],
    no_of_votes: 1516346,
    gross: '448,139,099',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: '3 Idiots',
    synopsis: 'Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.',
    year: 2009,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BNTkyOGVjMGEtNmQzZi00NzFlLTlhOWQtODYyMDc2ZGJmYzFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UY98_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.4,
    meta_score: 67,
    critics_score: 84,
    certificate: 'UA',
    duration: '170 min',
    genre: 'Comedy, Drama',
    director: 'Rajkumar Hirani',
    cast: ['Aamir Khan', 'Madhavan', 'Mona Singh', 'Sharman Joshi'],
    no_of_votes: 344445,
    gross: '6,532,908',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: 'HD, 5.1 Surround',
    resolution: 'HD',
    audio: '5.1 Surround',
  },
  {
    title: 'WALL·E',
    synopsis: 'In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.',
    year: 2008,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.4,
    meta_score: 95,
    critics_score: 84,
    certificate: 'U',
    duration: '98 min',
    genre: 'Animation, Adventure, Family',
    director: 'Andrew Stanton',
    cast: ['Ben Burtt', 'Elissa Knight', 'Jeff Garlin', 'Fred Willard'],
    no_of_votes: 999790,
    gross: '223,808,164',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Inglourious Basterds',
    synopsis: 'In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner\'s vengeful plans for the same.',
    year: 2009,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BOTJiNDEzOWYtMTVjOC00ZjlmLWE0NGMtZmE1OWVmZDQ2OWJhXkEyXkFqcGdeQXVyNTIzOTk5ODM@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.3,
    meta_score: 69,
    critics_score: 83,
    certificate: 'A',
    duration: '153 min',
    genre: 'Adventure, Drama, War',
    director: 'Quentin Tarantino',
    cast: ['Brad Pitt', 'Diane Kruger', 'Eli Roth', 'Mélanie Laurent'],
    no_of_votes: 1267869,
    gross: '120,540,719',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K HDR10, 5.1 Surround',
    resolution: '4K HDR10',
    audio: '5.1 Surround',
  },
  {
    title: 'Good Will Hunting',
    synopsis: 'Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.',
    year: 1997,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.3,
    meta_score: 70,
    critics_score: 83,
    certificate: 'U',
    duration: '126 min',
    genre: 'Drama, Romance',
    director: 'Gus Van Sant',
    cast: ['Robin Williams', 'Matt Damon', 'Ben Affleck', 'Stellan Skarsgård'],
    no_of_votes: 861606,
    gross: '138,433,435',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: 'HD, 5.1 Surround',
    resolution: 'HD',
    audio: '5.1 Surround',
  },
  {
    title: 'Coco',
    synopsis: "Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.",
    year: 2017,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_UY98_CR1,0,67,98_AL_.jpg',
    imdb_rating: 8.4,
    meta_score: 81,
    critics_score: 84,
    certificate: 'U',
    duration: '105 min',
    genre: 'Animation, Adventure, Family',
    director: 'Lee Unkrich',
    cast: ['Anthony Gonzalez', 'Gael García Bernal', 'Benjamin Bratt', 'Alanna Ubach'],
    no_of_votes: 384171,
    gross: '209,726,015',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Dangal',
    synopsis: 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.',
    year: 2016,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTQ4MzQzMzM2Nl5BMl5BanBnXkFtZTgwMTQ1NzU3MDI@._V1_UY98_CR1,0,67,98_AL_.jpg',
    imdb_rating: 8.4,
    critics_score: 84,
    certificate: 'U',
    duration: '161 min',
    genre: 'Action, Biography, Drama',
    director: 'Nitesh Tiwari',
    cast: ['Aamir Khan', 'Sakshi Tanwar', 'Fatima Sana Shaikh', 'Sanya Malhotra'],
    no_of_votes: 156479,
    gross: '12,391,761',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: 'HD, 5.1 Surround',
    resolution: 'HD',
    audio: '5.1 Surround',
  },
  {
    title: '1917',
    synopsis: 'April 6th, 1917. As a regiment assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.',
    year: 2019,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BOTdmNTFjNDEtNzg0My00ZjkxLTg1ZDAtZTdkMDc2ZmFiNWQ1XkEyXkFqcGdeQXVyNTAzNzgwNTg@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.3,
    meta_score: 78,
    critics_score: 83,
    certificate: 'R',
    duration: '119 min',
    genre: 'Drama, Thriller, War',
    director: 'Sam Mendes',
    cast: ['Dean-Charles Chapman', 'George MacKay', 'Daniel Mays', 'Colin Firth'],
    no_of_votes: 425844,
    gross: '159,227,644',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: true,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, Dolby Atmos',
    resolution: '4K Dolby Vision',
    audio: 'Dolby Atmos',
  },
  {
    title: 'Eternal Sunshine of the Spotless Mind',
    synopsis: 'When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.',
    year: 2004,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.3,
    meta_score: 89,
    critics_score: 83,
    certificate: 'UA',
    duration: '108 min',
    genre: 'Drama, Romance, Sci-Fi',
    director: 'Michel Gondry',
    cast: ['Jim Carrey', 'Kate Winslet', 'Tom Wilkinson', 'Gerry Robert Byrne'],
    no_of_votes: 911664,
    gross: '34,400,301',
    hls_stream_url: HLS_STREAMS[1],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: 'HD, 5.1 Surround',
    resolution: 'HD',
    audio: '5.1 Surround',
  },
  {
    title: 'Toy Story',
    synopsis: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.",
    year: 1995,
    poster_url: 'https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_UX67_CR0,0,67,98_AL_.jpg',
    imdb_rating: 8.3,
    meta_score: 95,
    critics_score: 83,
    certificate: 'U',
    duration: '81 min',
    genre: 'Animation, Adventure, Comedy',
    director: 'John Lasseter',
    cast: ['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim Varney'],
    no_of_votes: 887429,
    gross: '191,796,233',
    hls_stream_url: HLS_STREAMS[0],
    critics_picks: false,
    trending: false,
    content_type: 'Movie',
    technical_specs: '4K Dolby Vision, 5.1 Surround',
    resolution: '4K Dolby Vision',
    audio: '5.1 Surround',
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB Atlas');

    // Clear existing content
    await Content.deleteMany({});
    console.log('🗑️  Cleared existing content collection');

    // Insert seed data
    const inserted = await Content.insertMany(seedData);
    console.log(`🌱 Seeded ${inserted.length} content documents:`);
    inserted.forEach((item) => {
      console.log(`   • ${item.title} (${item._id}) — IMDB: ${item.imdb_rating}`);
    });

    console.log('\n✅ Seeding complete!');
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
}

seed();
